// Mocks generated by Mockito 5.4.6 from annotations
// in uangku/test/features/export/providers/export_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_analytics/firebase_analytics.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uangku/core/services/monitoring_service.dart' as _i3;
import 'package:uangku/data/database.dart' as _i10;
import 'package:uangku/data/models/category_spending.dart' as _i7;
import 'package:uangku/data/models/daily_spending.dart' as _i8;
import 'package:uangku/data/models/monthly_summary.dart' as _i9;
import 'package:uangku/data/models/transaction_with_category.dart' as _i6;
import 'package:uangku/data/models/transaction_with_details.dart' as _i12;
import 'package:uangku/data/repositories/transaction_repository.dart' as _i5;
import 'package:uangku/data/tables/transactions_table.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseAnalyticsObserver_0 extends _i1.SmartFake
    implements _i2.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonitoringService extends _i1.Mock implements _i3.MonitoringService {
  MockMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseAnalyticsObserver get observer =>
      (super.noSuchMethod(
            Invocation.getter(#observer),
            returnValue: _FakeFirebaseAnalyticsObserver_0(
              this,
              Invocation.getter(#observer),
            ),
          )
          as _i2.FirebaseAnalyticsObserver);

  @override
  _i4.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordError(
    dynamic exception,
    StackTrace? stack, {
    dynamic reason,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [exception, stack],
              {#reason: reason, #fatal: fatal},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> log(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#log, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void logInfo(String? message, [Map<String, Object>? context]) =>
      super.noSuchMethod(
        Invocation.method(#logInfo, [message, context]),
        returnValueForMissingStub: null,
      );

  @override
  void logError(
    String? message,
    dynamic exception,
    StackTrace? stack, [
    Map<String, Object>? context,
  ]) => super.noSuchMethod(
    Invocation.method(#logError, [message, exception, stack, context]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i5.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i6.TransactionWithCategory>> watchTransactionsByWallet(
    int? walletId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactionsByWallet, [walletId]),
            returnValue: _i4.Stream<List<_i6.TransactionWithCategory>>.empty(),
          )
          as _i4.Stream<List<_i6.TransactionWithCategory>>);

  @override
  _i4.Stream<List<_i6.TransactionWithCategory>> watchTransactionsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactionsByDateRange, [start, end]),
            returnValue: _i4.Stream<List<_i6.TransactionWithCategory>>.empty(),
          )
          as _i4.Stream<List<_i6.TransactionWithCategory>>);

  @override
  _i4.Stream<List<_i7.CategorySpending>> watchCategorySpending(
    DateTime? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchCategorySpending, [month]),
            returnValue: _i4.Stream<List<_i7.CategorySpending>>.empty(),
          )
          as _i4.Stream<List<_i7.CategorySpending>>);

  @override
  _i4.Stream<List<_i8.DailySpending>> watchDailySpending(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#watchDailySpending, [month]),
            returnValue: _i4.Stream<List<_i8.DailySpending>>.empty(),
          )
          as _i4.Stream<List<_i8.DailySpending>>);

  @override
  _i4.Stream<_i9.MonthlySummary> watchMonthlySummary(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#watchMonthlySummary, [month]),
            returnValue: _i4.Stream<_i9.MonthlySummary>.empty(),
          )
          as _i4.Stream<_i9.MonthlySummary>);

  @override
  _i4.Future<int> createTransaction(_i10.TransactionsCompanion? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> insertTransactionAndUpdateBalance({
    required _i10.TransactionsCompanion? transaction,
    required int? walletId,
    required double? balanceDelta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransactionAndUpdateBalance, [], {
              #transaction: transaction,
              #walletId: walletId,
              #balanceDelta: balanceDelta,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<List<_i6.TransactionWithCategory>> watchRecentTransactions(
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentTransactions, [limit]),
            returnValue: _i4.Stream<List<_i6.TransactionWithCategory>>.empty(),
          )
          as _i4.Stream<List<_i6.TransactionWithCategory>>);

  @override
  _i4.Stream<List<_i6.TransactionWithCategory>> watchAllTransactions({
    int? walletId,
    _i11.TransactionType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTransactions, [], {
              #walletId: walletId,
              #type: type,
            }),
            returnValue: _i4.Stream<List<_i6.TransactionWithCategory>>.empty(),
          )
          as _i4.Stream<List<_i6.TransactionWithCategory>>);

  @override
  _i4.Future<void> deleteTransactionAtomic(_i10.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransactionAtomic, [transaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTransactionAtomic({
    required int? transactionId,
    required _i10.TransactionsCompanion? updated,
    required int? walletId,
    required double? balanceDelta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransactionAtomic, [], {
              #transactionId: transactionId,
              #updated: updated,
              #walletId: walletId,
              #balanceDelta: balanceDelta,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> performInternalTransfer({
    required int? fromWalletId,
    required int? toWalletId,
    required double? amount,
    required DateTime? date,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#performInternalTransfer, [], {
              #fromWalletId: fromWalletId,
              #toWalletId: toWalletId,
              #amount: amount,
              #date: date,
              #note: note,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i12.TransactionWithDetails>>
  getAllTransactionsWithDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactionsWithDetails, []),
            returnValue: _i4.Future<List<_i12.TransactionWithDetails>>.value(
              <_i12.TransactionWithDetails>[],
            ),
          )
          as _i4.Future<List<_i12.TransactionWithDetails>>);
}
