// Mocks generated by Mockito 5.4.6 from annotations
// in uangku/test/features/sync/state/sync_status_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uangku/data/database.dart' as _i5;
import 'package:uangku/data/repositories/wallet_repository.dart' as _i4;
import 'package:uangku/features/auth/models/user_profile.dart' as _i7;
import 'package:uangku/features/auth/repository/auth_repository.dart' as _i6;
import 'package:uangku/features/sync/repository/sync_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SyncRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncRepository extends _i1.Mock implements _i2.SyncRepository {
  MockSyncRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> syncTransaction(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#syncTransaction, [transactionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [transactionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> syncCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#syncCategory, [categoryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [categoryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> syncWallet(int? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#syncWallet, [walletId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWallet(int? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWallet, [walletId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> syncFromCloud() =>
      (super.noSuchMethod(
            Invocation.method(#syncFromCloud, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i4.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i5.Wallet>> watchAllWallets() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllWallets, []),
            returnValue: _i3.Stream<List<_i5.Wallet>>.empty(),
          )
          as _i3.Stream<List<_i5.Wallet>>);

  @override
  _i3.Future<int> createWallet(_i5.WalletsCompanion? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, [wallet]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateWallet(_i5.WalletsCompanion? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#updateWallet, [wallet]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteWallet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWallet, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i5.Wallet?> getWalletById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWalletById, [id]),
            returnValue: _i3.Future<_i5.Wallet?>.value(),
          )
          as _i3.Future<_i5.Wallet?>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i7.UserProfile?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i7.UserProfile?>.empty(),
          )
          as _i3.Stream<_i7.UserProfile?>);

  @override
  _i3.Future<_i7.UserProfile?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i7.UserProfile?>.value(),
          )
          as _i3.Future<_i7.UserProfile?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
